### ISSUE TITLE
use proper email (both source + destination accounts)

### ISSUE THREAD

**Issue by joelmarkanderson** [IQSS/dataverse-aws#1]
consider donotreply@dataverse.[institution] for source
consider dataverse@[institution] for destination

**Comment by telnoratti** [comment]
Most mail relays are not open relays (correctly so). It doesn't appear that dataverse, or at least the install script doesn't.

Proposal is that we have a checkbox that optionally allows using an SES relay `email-smtp.us-east-1.amazonaws.com` or region appropriate relay rather than a user provided relay. We would need a field to provide the arn to use for the identity it is sending from i.e. `arn:aws:ses:us-east-1:00000000000:identity/dataverse@vtti.vt.edu`. This is unavoidably a manual setup process to verify the identity, so we would just need to consume it.

We also need to distinguish between the dataverseAdmin email and the administrative email. Currently those are both `AdminEmail`.

**Comment by pdurbin** [comment]
The relay stuff reminds me of https://github.com/IQSS/dataverse/issues/3061

**Comment by telnoratti** [comment]
It may be easier then to use asadmin to modify the existing javamail resource to use a password.

**Comment by telnoratti** [comment]
Authenticated smtp relay support was added in 32fa7a812f72ac53469196a65b280028fadfe370

We will also want to be sure that the dataverseAdmin email is getting changed correctly. It doesn't look like this is the case now.

**Comment by telnoratti** [comment]
Setting dataverseAdmin email correctly was finished in 857a29b275e22eb462e824207055ef64161d0f2b.
